const express = require('express')
const app = express()
app.use(express.json())
const userController = require('../controllers/user.controller')
const auth = require('../auth/auth')
const { checkRole } = require('../middleware/checkrole')
app.post("/login", userController.login)
app.get("/getAllUser", auth.authVerify, checkRole(["admin","resepsionis"]), userController.getAllUser)
// app.get("/findOne/:id", authVerify, checkRole(["admin","resepsionis"]), userController.findAllUser)
// app.delete("/:id", auth.authVerify, checkRole(["admin"]), userController.deleteUser)
// app.put("/:id", userController.updateUser)
// app.get("/findAllCustomer",  userController.findAllCustomer)
// app.post("/RegisterCustomer", userController.RegisterCustomer)
app.post("/RegisterLoginCustomer", userController.LoginRegister)
// app.get("/getUserCount", userController.getUserLength)
app.post("/", userController.addUser)
module.exports = app